#!/usr/bin/env python3
# dragonFM command line filemanager
# By Chrys, Storm Dragon, and contributers.

import os, sys, inspect
dragonfmPath = os.path.dirname(os.path.realpath(os.path.abspath(inspect.getfile(inspect.currentframe()))))

if not dragonfmPath in sys.path:
    sys.path.append(dragonfmPath)

from dragonfilemanager.core import dragonfmManager

def main():
    app = dragonfmManager.dragonfmManager()
    app.start()
    del app

if __name__ == "__main__":
    main()
